apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sg1hwgi9r-python
  janus-idp.io/tekton: sg1hwgi9r-python
  backstage.io/kubernetes-id: sg1hwgi9r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sg1hwgi9r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
